[package]
name = "gameops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "3.0.3"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0.89"
threadpool = "1.8.1"